# Generated by Django 4.2.23 on 2025-07-16 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileImage', models.ImageField(blank=True, null=True, upload_to='profileImages/')),
                ('Gender', models.IntegerField(choices=[(1, 'مرد'), (2, 'زن')], default=1)),
                ('Credit', models.IntegerField(default=0)),
                ('role', models.CharField(choices=[('user', 'کاربر'), ('vendor', 'فروشنده'), ('admin', 'مدیر')], default='user', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
